# Source Files 
BTLEROOT=../../../../..

# BTLESRC = $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/main.c 
# BTLESRC += $(BTLEROOT)system_stm32l4xx.o 
# BTLESRC += $(BTLEROOT)startup_stm32l476xx.o
BTLESRC = $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/AudioBV_Manager.c 
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/MotionCP_Manager.c 
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/MotionGR_Manager.c 
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/HWAdvanceFeatures.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/MotionAR_Manager.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/stm32l4xx_hal_msp.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/OTA.c
# BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/stm32l4xx_it.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/TargetPlatform.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/usbd_conf.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/sensor_service.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/hts221/HTS221_Driver_HL.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/usbd_cdc_interface.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/hts221/HTS221_Driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lps22hb/LPS22HB_Driver_HL.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lps22hb/LPS22HB_Driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm303agr/LSM303AGR_MAG_driver_HL.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm303agr/LSM303AGR_ACC_driver_HL.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm303agr/LSM303AGR_MAG_driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm303agr/LSM303AGR_ACC_driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm6dsm/LSM6DSM_ACC_GYRO_driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/lsm6dsm/LSM6DSM_ACC_GYRO_driver_HL.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/Components/stc3115/STC3115_Driver.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_BlueNRG.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_accelero.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_audio_in.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_gg.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_gyro.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_humidity.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_magneto.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_pressure.c
BTLESRC += $(BTLEROOT)/Drivers/BSP/SensorTile/SensorTile_temperature.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c
gBTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c
BTLESRC += $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/Interface/bluenrg_itf_template.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gap_aci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gatt_aci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_hal_aci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_l2cap_aci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_updater_aci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_utils.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/hci.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/utils/ble_list.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/utils/gp_timer.c
# BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/utils/osal.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_MetaDataManager/MetaDataManager.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
BTLESRC += $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/MotionFX_Manager.c
BTLESRC += $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Src/usbd_desc.c

BTLEINC = $(BTLEROOT)/Projects/Multi/Applications/BlueMicrosystem2/Inc
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_MetaDataManager 
BTLEINC+= $(BTLEROOT)/Drivers/CMSIS/Device/ST/STM32L4xx/Include 
BTLEINC+= $(BTLEROOT)/Drivers/STM32L4xx_HAL_Driver/Inc 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/SensorTile 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/Common 
BTLEINC+= $(BTLEROOT)/Drivers/CMSIS/Include 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/lsm6dsm 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/hts221 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/lps22hb 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/lsm303agr 
BTLEINC+= $(BTLEROOT)/Drivers/BSP/Components/stc3115 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_USB_Device_Library/Core/Inc 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_OSX_MotionFX_Library/Inc 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_OSX_MotionAR_Library/Inc 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_OSX_MotionCP_Library/Inc 
BTLEINC+= $(BTLEROOT)/Middlewares/ST/STM32_OSX_MotionGR_Library/Inc 
BTLEINC+=  $(BTLEROOT)/Middlewares/ST/STM32_OSX_BlueVoice_Library/Inc 

# Compiler defined variables 
BTLEVARS+= -DSTM32_SENSORTILE
BTLEVARS+= -D_RTE_ -DSTM32L476xx 
BTLEVARS+= -DSTM32L476xx 
BTLEVARS+= -DUSE_HAL_DRIVER 
BTLEVARS+= -DUSE_STM32L4XX_NUCLEO 
BTLEVARS+= -D__BYTE_ORDER=0
